version: "3.3"
services:
    app:
        build: .
        container_name: pest-test
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network
        restart: always
networks:
    app-network:
        driver: bridge
